# Generated by Django 5.2.3 on 2025-08-22 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('timestamped_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.timestamped')),
                ('booking_date', models.DateTimeField(help_text='Date and time of the booking')),
                ('booking_status', models.CharField(choices=[('pending', 'pending'), ('confirmed', 'confirmed'), ('cancelled', 'cancelled'), ('completed', 'completed')], default='pending', help_text='Current status of the booking', max_length=30)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the booking')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'bookings',
                'ordering': ['-booking_date'],
            },
            bases=('common.timestamped',),
        ),
    ]
