# Generated by Django 5.2.3 on 2025-08-22 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(help_text='The service being booked', on_delete=django.db.models.deletion.PROTECT, to='services.service'),
        ),
    ]
