# Generated by Django 5.2.3 on 2025-08-22 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(help_text='The student making the order', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(help_text='The parent order', on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='services.order'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(help_text='The user writing the review', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='service',
            name='vendor',
            field=models.ForeignKey(help_text='The vendor offering this service', on_delete=django.db.models.deletion.PROTECT, related_name='services', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='service',
            field=models.ForeignKey(help_text='The service being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='services.service'),
        ),
        migrations.AddField(
            model_name='order',
            name='service',
            field=models.ForeignKey(help_text='The service being ordered', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='services.service'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='service',
            field=models.ForeignKey(help_text='The parent service', on_delete=django.db.models.deletion.CASCADE, related_name='service_items', to='services.service'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='service_item',
            field=models.ForeignKey(help_text='The service item being ordered', on_delete=django.db.models.deletion.CASCADE, to='services.serviceitem'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='user',
            field=models.OneToOneField(help_text='The vendor user account', on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(fields=('vendor', 'service_name'), name='unique_vendor_service', violation_error_message='You already have a service with this name.'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('service', 'user'), name='unique_user_service_review', violation_error_message='You can only review a service once.'),
        ),
        migrations.AddConstraint(
            model_name='serviceitem',
            constraint=models.UniqueConstraint(fields=('service', 'name'), name='unique_service_item', violation_error_message='This service already has an item with this name.'),
        ),
    ]
