# Generated by Django 5.2.3 on 2025-06-27 00:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_rating_service_total_ratings_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='requires_contact',
            field=models.BooleanField(default=False, help_text='Whether this service requires direct contact'),
        ),
        migrations.AddField(
            model_name='service',
            name='supports_booking',
            field=models.BooleanField(default=False, help_text='Whether this service supports booking/appointments'),
        ),
        migrations.AddField(
            model_name='service',
            name='supports_ordering',
            field=models.BooleanField(default=False, help_text='Whether this service supports ordering'),
        ),
        migrations.AddField(
            model_name='service',
            name='supports_walk_in',
            field=models.BooleanField(default=False, help_text='Whether this service supports walk-ins'),
        ),
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(help_text='Official business name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Business description', null=True)),
                ('business_hours', models.TextField(blank=True, help_text='Operating hours (e.g., Mon-Fri 9AM-6PM)', null=True)),
                ('address', models.CharField(blank=True, help_text='Physical business address', max_length=500, null=True)),
                ('phone', models.CharField(blank=True, help_text='Business phone number', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, help_text='Business email address', max_length=254, null=True)),
                ('website', models.URLField(blank=True, help_text='Business website URL', null=True)),
                ('logo', models.ImageField(blank=True, help_text='Business logo', null=True, upload_to='vendor_logos/')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether the business is verified by admin')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the business is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when profile was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when profile was last updated')),
                ('user', models.OneToOneField(help_text='The vendor user account', on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendor Profile',
                'verbose_name_plural': 'Vendor Profiles',
                'ordering': ['business_name'],
            },
        ),
    ]
