# Generated by Django 5.2.3 on 2025-09-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_requires_contact_service_supports_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='airtel_money_number',
            field=models.CharField(blank=True, help_text='Airtel Money number', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='mtn_momo_number',
            field=models.CharField(blank=True, help_text='MTN Mobile Money number', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='preferred_payment_method',
            field=models.CharField(choices=[('mtn_momo', 'MTN Mobile Money'), ('vodafone_cash', 'Vodafone Cash'), ('airtel_money', 'Airtel Money'), ('telecel_cash', 'Telecel Cash'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash Payment')], default='mtn_momo', help_text='Preferred payment method', max_length=20),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='telecel_cash_number',
            field=models.CharField(blank=True, help_text='Telecel Cash number', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='vodafone_cash_number',
            field=models.CharField(blank=True, help_text='Vodafone Cash number', max_length=15, null=True),
        ),
    ]
