# Generated by Django 5.2.3 on 2025-09-17 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_service_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='The document to print', upload_to='print_requests/%Y/%m/%d/')),
                ('copies', models.PositiveIntegerField(default=1, help_text='Number of copies requested')),
                ('paper_size', models.CharField(choices=[('A4', 'A4'), ('A3', 'A3'), ('Letter', 'Letter'), ('Legal', 'Legal')], default='A4', help_text='Size of paper', max_length=10)),
                ('color_mode', models.CharField(choices=[('black_white', 'Black & White'), ('color', 'Color')], default='black_white', help_text='Color or black & white printing', max_length=20)),
                ('special_instructions', models.TextField(blank=True, help_text='Any special printing requirements')),
                ('contact_phone', models.CharField(blank=True, help_text="Student's contact phone number", max_length=15)),
                ('pickup_location', models.CharField(blank=True, help_text='Where to pick up the printed documents', max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready for Pickup'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the print request', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when request was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when request was last updated')),
                ('service', models.ForeignKey(help_text='The printing service', on_delete=django.db.models.deletion.CASCADE, related_name='print_requests', to='services.service')),
                ('student', models.ForeignKey(help_text='The student making the request', on_delete=django.db.models.deletion.CASCADE, related_name='print_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Print Request',
                'verbose_name_plural': 'Print Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
