# Generated by Django 5.2.3 on 2025-08-22 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('card', 'Card Payment'), ('bank_transfer', 'Bank Transfer')], help_text='Method used for payment', max_length=20)),
                ('mobile_money_provider', models.CharField(blank=True, choices=[('mtn', 'MTN Mobile Money'), ('vodafone', 'Vodafone Cash'), ('airtel', 'AirtelTigo Money'), ('telecel', 'Telecel Cash')], help_text='Mobile money provider (if mobile money payment)', max_length=20, null=True)),
                ('transaction_id', models.CharField(help_text='Unique identifier for the payment transaction', max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('successful', 'Successful'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', help_text='Current status of the payment', max_length=20)),
                ('phone_number', models.CharField(blank=True, help_text='Phone number used for mobile money payment', max_length=15, null=True)),
                ('reference_number', models.CharField(blank=True, help_text='External reference number from payment provider', max_length=100, null=True)),
                ('payment_notes', models.TextField(blank=True, help_text='Additional notes about the payment', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when payment was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when payment was last updated')),
                ('booking', models.ForeignKey(blank=True, help_text='The booking this payment is for', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
