# Generated by Django 5.2.3 on 2025-08-22 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(blank=True, help_text='The order this payment is for', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='services.order'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('booking__isnull', False), ('order__isnull', False), _connector='OR'), name='payment_has_booking_or_order', violation_error_message='Payment must be associated with either a booking or order.'),
        ),
    ]
