# Generated by Django 5.2.3 on 2025-08-04 00:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(help_text='Name of the business', max_length=200)),
                ('business_description', models.TextField(help_text='Description of the business')),
                ('category', models.CharField(choices=[('food', 'Food & Beverages'), ('beauty', 'Beauty & Grooming'), ('printing', 'Printing & Copying'), ('laundry', 'Laundry Services'), ('academic', 'Academic Services'), ('transport', 'Transportation'), ('health', 'Health & Wellness'), ('entertainment', 'Entertainment'), ('other', 'Other Services')], help_text='Business category', max_length=20)),
                ('address', models.CharField(help_text='Business address', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Current status of the application', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Admin notes on the application', null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, help_text='When the application was submitted')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the application was reviewed', null=True)),
                ('applicant', models.ForeignKey(help_text='The user applying to become a vendor', on_delete=django.db.models.deletion.CASCADE, related_name='vendor_applications', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who reviewed this application', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendor Application',
                'verbose_name_plural': 'Vendor Applications',
                'ordering': ['-submitted_at'],
                'constraints': [models.UniqueConstraint(fields=('applicant',), name='unique_vendor_application_per_user', violation_error_message='You have already submitted a vendor application.')],
            },
        ),
    ]
