# Generated by Django 5.2.3 on 2025-08-24 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_blacklistedtoken'),
    ]

    operations = [
    ]
