# Generated by Django 5.2.3 on 2025-09-11 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_vendorapplication'),
        ('users', '0004_vendorapplication_email_vendorapplication_experience_and_more'),
    ]

    operations = [
    ]
