# Generated by Django 5.2.3 on 2025-09-11 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_merge_20250911_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorapplication',
            name='email',
            field=models.EmailField(blank=True, help_text='Business email address', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='vendorapplication',
            name='experience',
            field=models.TextField(blank=True, help_text='Business experience and background', null=True),
        ),
        migrations.AddField(
            model_name='vendorapplication',
            name='phone',
            field=models.CharField(blank=True, help_text='Business phone number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vendorapplication',
            name='reason',
            field=models.TextField(blank=True, help_text='Reason for wanting to join the platform', null=True),
        ),
        migrations.AddField(
            model_name='vendorapplication',
            name='website',
            field=models.URLField(blank=True, help_text='Business website URL', null=True),
        ),
    ]
