# Generated by Django 5.2.3 on 2025-09-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_vendorapplication_email_vendorapplication_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorapplication',
            name='category',
            field=models.CharField(choices=[('food', 'Food & Beverages'), ('beauty', 'Beauty & Grooming'), ('printing', 'Printing & Copying'), ('laundry', 'Laundry Services'), ('academic', 'Academic Services'), ('transport', 'Transportation'), ('health', 'Health & Wellness'), ('entertainment', 'Entertainment'), ('gym', 'Gym & Fitness'), ('other', 'Other Services')], help_text='Business category', max_length=20),
        ),
    ]
